Add support for DNF (Yum v4) property `install_weak_deps`
sous-chefs/yum pull request #194
Opened 2021-08-26 23:02 UTC by newatlantis

Signed-off-by: Lincoln Abbey <linc.abbey@gmail.com>

# Description

Describe what this change achieves

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2021-08-28 10:00 UTC, bmhughes requested changes

2021-08-28 10:00 UTC, bmhughes commented on README.md
> +#### Yum v4 DNF Properties
The weak deps options is valid for yum as well so just put it under the original `#### Properties` header.

2021-08-28 10:00 UTC, bmhughes commented
Just a couple of small changes and this is good to go.

2021-08-28 21:10 UTC, newatlantis reviewed
Thank you for your help with this PR. I'm still getting used to the GitHub interface and capabilities. So I hope I did it right. I added some comments (more like questions) to the PR itself, hoping I could get your feedback on a few points that are not clear to me. Please let me know if you see me not following the desired process here correctly!

2021-08-28 21:10 UTC, newatlantis commented on CHANGELOG.md
> +- Add support for DNF (Yum v4) property `install_weak_deps` (#193)
OK, I think I understand what you mean. Thank you, I didn't know that. Did that.

2021-08-28 21:42 UTC, newatlantis commented
> Just a couple of small changes and this is good to go.

@bmhughes: I tried to address the two changes I saw you request, to the CHANGELOG.md and README.md files. It looks like the CI build has passed. But I see above the message that "Merging can be performed automatically once the requested changes are addressed." Could I trouble you to point out to me what I need to do next for this PR? Thanks for all your help.

2021-08-29 14:55 UTC, bmhughes commented on test/fixtures/cookbooks/yum_test/recipes/test_globalconfig_two.rb
> +  install_weak_deps false
This is fine (initially at least)

2021-08-29 14:59 UTC, bmhughes requested changes

2021-08-29 14:59 UTC, bmhughes commented on templates/main.erb
> +<% unless @config.install_weak_deps.nil? %>
You don't need the double negative of `unless` and the `.nil?` call and the additional if/else block.

You can just do `if @config.install_weak_deps` as the other properties are and then use `coerce` on the property to set the integer value higher up the call stack. I've put what I mean as a comment against the property declaration. The default value is true so we can set that by default without issue.

2021-08-29 14:59 UTC, bmhughes commented on resources/globalconfig.rb
> +property :install_weak_deps, [true, false], description: "When this option is set to true and a new package is about to be installed, all packages linked by a weak dependency relation (i.e., Recommen
```property :install_weak_deps, [true, false], default: true, coerce: proc { |p| p ? 1 : 0 }, description: "When this option is set to true and a new package is about to be installed, all packages linked by a weak dependency relation (i.e., Recommends or Supplements flags) with this package will be pulled into the transaction. Default is DNF's default of true."```

2021-08-29 15:03 UTC, bmhughes commented on templates/main.erb
> +<% unless @config.install_weak_deps.nil? %>
We can drop all of this and just do a check against the property value being false and then set `install_weak_deps=0`, the default value is true so we don't need to worry about it until it's needed to be set to false.

2021-08-29 15:04 UTC, bmhughes commented
> 
> 
> > Just a couple of small changes and this is good to go.
> 
> @bmhughes: I tried to address the two changes I saw you request, to the CHANGELOG.md and README.md files. It looks like the CI build has passed. But I see above the message that "Merging can be performed automatically once the requested changes are addressed." Could I trouble you to point out to me what I need to do next for this PR? Thanks for all your help.

That'll dissapear once I (or someone else) approves the PR.

2021-08-29 18:43 UTC, ramereth approved these changes

2021-08-29 18:44 UTC, merged

2021-08-29 18:44 UTC, kitchen-porter commented
Released as: [7.1.0](https://github.com/sous-chefs/yum/releases/tag/7.1.0)